name: iOS Build

on: workflow_dispatch

jobs:
  build:
    name: iOS Build
    permissions: write-all
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
          
      - name: Install Libraries
        run: |
         haxelib install hxpkg --global
         haxelib run hxpkg setup --global
         haxelib run hxpkg install
         haxelib remove lime
         haxelib git lime https://github.com/FunkinCrew/lime mobile/main --quiet
         haxelib run lime rebuild hxcpp
      - name: Compile
        run: haxelib run lime build ios -nosign

      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/NightmereVision.app
          ldid -S../../../NightmereVision/NightmereVision.entitlements NightmereVision
          cd ..
          mkdir Payload
          mv NightmereVision.app Payload
          zip -r NightmereVision.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: NightmereVision iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error